spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/account"
    username: "postgres"
    password: "postgres"
    driver-class-name: "org.postgresql.Driver"

server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
